import { BoardSpace, DistrictColor } from '../engines/types';

export const BOARD_SPACES: BoardSpace[] = [
  // 0: GO
  {
    id: 0,
    name: 'African Union Gateway (GO)',
    type: 'GO',
    subtitle: 'Collect $200 Continental Stipend',
    landmarkKey: 'african_gateway',
  },
  // 1: Nile Valley & Red Sea 1 (Alexandria, Egypt)
  {
    id: 1,
    name: 'Alexandria Qaitbay Citadel',
    type: 'PROPERTY',
    district: 'sepia',
    price: 60,
    rent: [2, 10, 30, 90, 160, 250],
    houseCost: 50,
    mortgageValue: 30,
    subtitle: 'Historic Mediterranean Fortress, Egypt',
    landmarkKey: 'alexandria_qaitbay',
  },
  // 2: Vault Chest
  {
    id: 2,
    name: 'African Sovereign Vault',
    type: 'VAULT',
    subtitle: 'Draw Sovereign Vault Card',
    landmarkKey: 'vault_chest',
  },
  // 3: Nile Valley & Red Sea 2 (Aswan, Egypt)
  {
    id: 3,
    name: 'Aswan Philae Island Temple',
    type: 'PROPERTY',
    district: 'sepia',
    price: 60,
    rent: [4, 20, 60, 180, 320, 450],
    houseCost: 50,
    mortgageValue: 30,
    subtitle: 'Sanctuary of Isis on the Nile, Egypt',
    landmarkKey: 'aswan_philae',
  },
  // 4: Continental Development Assessment
  {
    id: 4,
    name: 'Pan-African Infrastructure Tariff',
    type: 'TAX',
    taxAmount: 200,
    subtitle: 'Pay $200 Development Assessment',
    landmarkKey: 'city_tax',
  },
  // 5: Transit 1 (Morocco High Speed)
  {
    id: 5,
    name: 'Al Boraq High-Speed Rail',
    type: 'TRANSIT',
    price: 200,
    rent: [25, 50, 100, 200],
    mortgageValue: 100,
    subtitle: 'Tangier-Casablanca Bullet Train, Morocco',
    landmarkKey: 'transit_al_boraq',
  },
  // 6: Imperial Maghreb 1 (Marrakech, Morocco)
  {
    id: 6,
    name: 'Marrakech Jemaa el-Fnaa',
    type: 'PROPERTY',
    district: 'cyan',
    price: 100,
    rent: [6, 30, 90, 270, 400, 550],
    houseCost: 50,
    mortgageValue: 50,
    subtitle: 'Historic Medina & Koutoubia Minaret, Morocco',
    landmarkKey: 'marrakech_jemaa',
  },
  // 7: Destiny Beacon
  {
    id: 7,
    name: 'Destiny Beacon',
    type: 'DESTINY',
    subtitle: 'Draw Destiny Opportunity Card',
    landmarkKey: 'destiny_beacon',
  },
  // 8: Imperial Maghreb 2 (Casablanca, Morocco)
  {
    id: 8,
    name: 'Casablanca Hassan II Mosque',
    type: 'PROPERTY',
    district: 'cyan',
    price: 100,
    rent: [6, 30, 90, 270, 400, 550],
    houseCost: 50,
    mortgageValue: 50,
    subtitle: 'Atlantic Ocean Minaret & Marble Plaza, Morocco',
    landmarkKey: 'casablanca_hassan',
  },
  // 9: Imperial Maghreb 3 (Chefchaouen, Morocco)
  {
    id: 9,
    name: 'Chefchaouen Blue Pearl',
    type: 'PROPERTY',
    district: 'cyan',
    price: 120,
    rent: [8, 40, 100, 300, 450, 600],
    houseCost: 50,
    mortgageValue: 60,
    subtitle: 'Iconic Cobalt Blue Rif Medina, Morocco',
    landmarkKey: 'chefchaouen_blue',
  },
  // 10: Detention & Sahara Outpost
  {
    id: 10,
    name: 'Interpol Saharan Detention',
    type: 'JAIL',
    subtitle: 'Just Visiting or Detained in Sahara',
    landmarkKey: 'city_detention',
  },
  // 11: Carthage & Mediterranean Gates 1 (Tunisia)
  {
    id: 11,
    name: 'Carthage Imperial Ruins',
    type: 'PROPERTY',
    district: 'magenta',
    price: 140,
    rent: [10, 50, 150, 450, 625, 750],
    houseCost: 100,
    mortgageValue: 70,
    subtitle: 'Punic Ports & Roman Antonine Baths, Tunisia',
    landmarkKey: 'carthage_ruins',
  },
  // 12: Utility 1 (Egypt)
  {
    id: 12,
    name: 'Aswan High Dam Hydro Core',
    type: 'UTILITY',
    price: 150,
    mortgageValue: 75,
    subtitle: 'Nile Hydroelectric Power Grid, Egypt',
    landmarkKey: 'aswan_dam',
  },
  // 13: Carthage & Mediterranean Gates 2 (Algeria)
  {
    id: 13,
    name: 'Algiers Casbah Citadel',
    type: 'PROPERTY',
    district: 'magenta',
    price: 140,
    rent: [10, 50, 150, 450, 625, 750],
    houseCost: 100,
    mortgageValue: 70,
    subtitle: 'Ottoman Whitewashed Hillside & Bay, Algeria',
    landmarkKey: 'algiers_casbah',
  },
  // 14: Carthage & Mediterranean Gates 3 (Algeria)
  {
    id: 14,
    name: 'Constantine Sidi M\'Cid Bridge',
    type: 'PROPERTY',
    district: 'magenta',
    price: 160,
    rent: [12, 60, 180, 500, 700, 900],
    houseCost: 100,
    mortgageValue: 80,
    subtitle: 'City of Bridges Rhumel Canyon, Algeria',
    landmarkKey: 'constantine_bridge',
  },
  // 15: Transit 2
  {
    id: 15,
    name: 'Trans-Sahara Express Rail',
    type: 'TRANSIT',
    price: 200,
    rent: [25, 50, 100, 200],
    mortgageValue: 100,
    subtitle: 'Continental Desert Rail Corridor',
    landmarkKey: 'transit_trans_sahara',
  },
  // 16: Sahara Oasis & Desert Wonders 1 (Libya)
  {
    id: 16,
    name: 'Ghadames Pearl Oasis',
    type: 'PROPERTY',
    district: 'amber',
    price: 180,
    rent: [14, 70, 200, 550, 750, 950],
    houseCost: 100,
    mortgageValue: 90,
    subtitle: 'Ancient Sahara Labyrinth City, Libya',
    landmarkKey: 'ghadames_oasis',
  },
  // 17: Vault Chest
  {
    id: 17,
    name: 'African Sovereign Vault',
    type: 'VAULT',
    subtitle: 'Draw Sovereign Vault Card',
    landmarkKey: 'vault_chest',
  },
  // 18: Sahara Oasis & Desert Wonders 2 (Libya)
  {
    id: 18,
    name: 'Leptis Magna Roman Forum',
    type: 'PROPERTY',
    district: 'amber',
    price: 180,
    rent: [14, 70, 200, 550, 750, 950],
    houseCost: 100,
    mortgageValue: 90,
    subtitle: 'Arch of Septimius Severus on Sea, Libya',
    landmarkKey: 'leptis_magna',
  },
  // 19: Sahara Oasis & Desert Wonders 3 (Mauritania)
  {
    id: 19,
    name: 'Richat Eye of the Sahara',
    type: 'PROPERTY',
    district: 'amber',
    price: 200,
    rent: [16, 80, 220, 600, 800, 1000],
    houseCost: 100,
    mortgageValue: 100,
    subtitle: 'Giant Geological Dome & Oasis, Mauritania',
    landmarkKey: 'richat_structure',
  },
  // 20: Serengeti Wildlife Haven
  {
    id: 20,
    name: 'Serengeti Reserve Haven',
    type: 'FREE_PARKING',
    subtitle: 'Continental Wildlife Oasis & Jackpot',
    landmarkKey: 'serengeti_haven',
  },
  // 21: Horn of Africa & Rift Highlands 1 (Ethiopia)
  {
    id: 21,
    name: 'Lalibela Rock Monoliths',
    type: 'PROPERTY',
    district: 'crimson',
    price: 220,
    rent: [18, 90, 250, 700, 875, 1050],
    houseCost: 150,
    mortgageValue: 110,
    subtitle: 'Bete Giyorgis Rock-Cut Cross, Ethiopia',
    landmarkKey: 'lalibela_church',
  },
  // 22: Destiny Beacon
  {
    id: 22,
    name: 'Destiny Beacon',
    type: 'DESTINY',
    subtitle: 'Draw Destiny Opportunity Card',
    landmarkKey: 'destiny_beacon',
  },
  // 23: Horn of Africa & Rift Highlands 2 (Kenya)
  {
    id: 23,
    name: 'Nairobi Savannah Horizon',
    type: 'PROPERTY',
    district: 'crimson',
    price: 220,
    rent: [18, 90, 250, 700, 875, 1050],
    houseCost: 150,
    mortgageValue: 110,
    subtitle: 'Modern Metropolis Wildlife Frontier, Kenya',
    landmarkKey: 'nairobi_skyline',
  },
  // 24: Horn of Africa & Rift Highlands 3 (Tanzania/Kenya)
  {
    id: 24,
    name: 'Mount Kilimanjaro Summit',
    type: 'PROPERTY',
    district: 'crimson',
    price: 240,
    rent: [20, 100, 300, 750, 925, 1100],
    houseCost: 150,
    mortgageValue: 120,
    subtitle: 'Roof of Africa Snowcapped Peak, Tanzania',
    landmarkKey: 'mount_kilimanjaro',
  },
  // 25: Transit 3 (Egypt-Sudan-Ethiopia corridor)
  {
    id: 25,
    name: 'Blue Nile Continental Rail',
    type: 'TRANSIT',
    price: 200,
    rent: [25, 50, 100, 200],
    mortgageValue: 100,
    subtitle: 'Trans-Nile International High-Rail',
    landmarkKey: 'transit_blue_nile',
  },
  // 26: Great Ancient Wonders 1 (Luxor, Egypt)
  {
    id: 26,
    name: 'Luxor Karnak Grand Temple',
    type: 'PROPERTY',
    district: 'gold',
    price: 260,
    rent: [22, 110, 330, 800, 975, 1150],
    houseCost: 150,
    mortgageValue: 130,
    subtitle: 'Hypostyle Hall & Avenue of Sphinxes, Egypt',
    landmarkKey: 'luxor_karnak',
  },
  // 27: Great Ancient Wonders 2 (Abu Simbel, Egypt)
  {
    id: 27,
    name: 'Abu Simbel Sun Temples',
    type: 'PROPERTY',
    district: 'gold',
    price: 260,
    rent: [22, 110, 330, 800, 975, 1150],
    houseCost: 150,
    mortgageValue: 130,
    subtitle: 'Colossal Ramses II Mountain Sculptures, Egypt',
    landmarkKey: 'abu_simbel',
  },
  // 28: Utility 2 (Morocco)
  {
    id: 28,
    name: 'Noor Ouarzazate Solar Complex',
    type: 'UTILITY',
    price: 150,
    mortgageValue: 75,
    subtitle: 'World\'s Largest Concentrated Solar Array, Morocco',
    landmarkKey: 'noor_solar',
  },
  // 29: Great Ancient Wonders 3 (Cairo, Egypt)
  {
    id: 29,
    name: 'Giza Great Pyramids & Sphinx',
    type: 'PROPERTY',
    district: 'gold',
    price: 280,
    rent: [24, 120, 360, 850, 1025, 1200],
    houseCost: 150,
    mortgageValue: 140,
    subtitle: 'The Last Standing Ancient World Wonder, Egypt',
    landmarkKey: 'giza_pyramids',
  },
  // 30: Federal Extradition Order
  {
    id: 30,
    name: 'Continental Extradition',
    type: 'GO_TO_JAIL',
    subtitle: 'Sent Directly to Saharan Detention',
    landmarkKey: 'detain_order',
  },
  // 31: Southern Sun & Natural Jewels 1 (Zimbabwe/Zambia)
  {
    id: 31,
    name: 'Victoria Falls Thunder Mist',
    type: 'PROPERTY',
    district: 'emerald',
    price: 300,
    rent: [26, 130, 390, 900, 1100, 1275],
    houseCost: 200,
    mortgageValue: 150,
    subtitle: 'The Smoke That Thunders on Zambezi',
    landmarkKey: 'victoria_falls',
  },
  // 32: Southern Sun & Natural Jewels 2 (Tanzania/Kenya)
  {
    id: 32,
    name: 'Serengeti Savannah Plain',
    type: 'PROPERTY',
    district: 'emerald',
    price: 300,
    rent: [26, 130, 390, 900, 1100, 1275],
    houseCost: 200,
    mortgageValue: 150,
    subtitle: 'Great Annual Wildebeest Migration Plains',
    landmarkKey: 'serengeti_plain',
  },
  // 33: Vault Chest
  {
    id: 33,
    name: 'African Sovereign Vault',
    type: 'VAULT',
    subtitle: 'Draw Sovereign Vault Card',
    landmarkKey: 'vault_chest',
  },
  // 34: Southern Sun & Natural Jewels 3 (South Africa)
  {
    id: 34,
    name: 'Cape Town Table Mountain',
    type: 'PROPERTY',
    district: 'emerald',
    price: 320,
    rent: [28, 150, 450, 1000, 1200, 1400],
    houseCost: 200,
    mortgageValue: 160,
    subtitle: 'Atlantic Ocean Flat-Topped Monolith, South Africa',
    landmarkKey: 'table_mountain',
  },
  // 35: Transit 4
  {
    id: 35,
    name: 'Cape to Cairo Continental Rail',
    type: 'TRANSIT',
    price: 200,
    rent: [25, 50, 100, 200],
    mortgageValue: 100,
    subtitle: 'Trans-Continental Grand Express Route',
    landmarkKey: 'transit_cape_cairo',
  },
  // 36: Destiny Beacon
  {
    id: 36,
    name: 'Destiny Beacon',
    type: 'DESTINY',
    subtitle: 'Draw Destiny Opportunity Card',
    landmarkKey: 'destiny_beacon',
  },
  // 37: Sovereign Island Paradises 1 (Zanzibar, Tanzania)
  {
    id: 37,
    name: 'Zanzibar Stone Town Palace',
    type: 'PROPERTY',
    district: 'navy',
    price: 350,
    rent: [35, 175, 500, 1100, 1300, 1500],
    houseCost: 200,
    mortgageValue: 175,
    subtitle: 'House of Wonders & Spice Island Waterfront',
    landmarkKey: 'zanzibar_palace',
  },
  // 38: African Diamond & Gold Tariff
  {
    id: 38,
    name: 'African Diamond & Gold Tariff',
    type: 'TAX',
    taxAmount: 100,
    subtitle: 'Pay $100 Sovereign Luxury Tariff',
    landmarkKey: 'luxury_tax',
  },
  // 39: Sovereign Island Paradises 2 (Seychelles)
  {
    id: 39,
    name: 'Seychelles Anse Source d\'Argent',
    type: 'PROPERTY',
    district: 'navy',
    price: 400,
    rent: [50, 200, 600, 1400, 1700, 2000],
    houseCost: 200,
    mortgageValue: 200,
    subtitle: 'Turquoise Lagoon & Pink Granite Monoliths',
    landmarkKey: 'seychelles_granite',
  },
];

export const DISTRICT_NAMES: Record<DistrictColor, string> = {
  sepia: 'Nile Valley',
  cyan: 'Imperial Maghreb',
  magenta: 'Carthage & Mediterranean',
  amber: 'Sahara Wonders',
  crimson: 'Rift Highlands',
  gold: 'Ancient Pharaonic',
  emerald: 'Southern Jewels',
  navy: 'Sovereign Islands',
};

export const DISTRICT_COLORS: Record<DistrictColor, { bg: string; text: string; border: string }> = {
  sepia: { bg: '#78350f', text: '#fef3c7', border: '#b45309' },
  cyan: { bg: '#0891b2', text: '#cffafe', border: '#06b6d4' },
  magenta: { bg: '#c026d3', text: '#fae8ff', border: '#d946ef' },
  amber: { bg: '#d97706', text: '#fef3c7', border: '#f59e0b' },
  crimson: { bg: '#dc2626', text: '#fee2e2', border: '#ef4444' },
  gold: { bg: '#ca8a04', text: '#fef9c3', border: '#eab308' },
  emerald: { bg: '#059669', text: '#d1fae5', border: '#10b981' },
  navy: { bg: '#1d4ed8', text: '#dbeafe', border: '#3b82f6' },
};
