import { Card } from '../engines/types';

export const DESTINY_CARDS: Card[] = [
  {
    id: 'destiny_1',
    deck: 'DESTINY',
    title: 'Advance to African Union Gateway',
    description: 'Advance directly to African Union Gateway (GO). Collect $200 continental stipend immediately.',
    effect: 'MOVE_TO',
    targetSpaceId: 0,
    icon: 'gate',
  },
  {
    id: 'destiny_2',
    deck: 'DESTINY',
    title: 'Victoria Falls Expedition',
    description: 'Advance to Victoria Falls Thunder Mist. If you pass African Gateway, collect $200.',
    effect: 'MOVE_TO',
    targetSpaceId: 31,
    icon: 'tower',
  },
  {
    id: 'destiny_3',
    deck: 'DESTINY',
    title: 'Carthage Heritage Forum',
    description: 'Advance to Carthage Imperial Ruins. If you pass African Gateway, collect $200.',
    effect: 'MOVE_TO',
    targetSpaceId: 11,
    icon: 'palette',
  },
  {
    id: 'destiny_4',
    deck: 'DESTINY',
    title: 'Pan-African Energy Grid Surge',
    description: 'Advance token to the nearest Public Utility (Aswan Dam or Noor Solar). If unowned, buy it. If owned, throw dice and pay 10 times the amount.',
    effect: 'MOVE_NEAREST_UTILITY',
    icon: 'zap',
  },
  {
    id: 'destiny_5',
    deck: 'DESTINY',
    title: 'Trans-African Rail Pass',
    description: 'Advance to the nearest Transit Terminal. If unowned, buy it. If owned, pay twice the normal rental fee.',
    effect: 'MOVE_NEAREST_TRANSIT',
    icon: 'train',
  },
  {
    id: 'destiny_6',
    deck: 'DESTINY',
    title: 'Trans-African Rail Pass',
    description: 'Advance to the nearest Transit Terminal. If unowned, buy it. If owned, pay twice the normal rental fee.',
    effect: 'MOVE_NEAREST_TRANSIT',
    icon: 'train',
  },
  {
    id: 'destiny_7',
    deck: 'DESTINY',
    title: 'African Development Bank Dividend',
    description: 'African Development Bank pays you a dividend of $50 from continental sovereign bonds.',
    effect: 'COLLECT_BANK',
    value: 50,
    icon: 'coins',
  },
  {
    id: 'destiny_8',
    deck: 'DESTINY',
    title: 'Interpol Pardon Pass',
    description: 'This diplomatic pass may be kept until needed, or traded. Releases you immediately from Saharan Detention.',
    effect: 'JAIL_FREE',
    icon: 'key',
  },
  {
    id: 'destiny_9',
    deck: 'DESTINY',
    title: 'Sahara Caravan Detour',
    description: 'Desert restoration detour. Move back 3 spaces.',
    effect: 'MOVE_RELATIVE',
    value: -3,
    icon: 'rewind',
  },
  {
    id: 'destiny_10',
    deck: 'DESTINY',
    title: 'Continental Extradition Warrant',
    description: 'Go directly to Saharan Detention. Do not pass African Gateway. Do not collect $200.',
    effect: 'GO_TO_JAIL',
    icon: 'lock',
  },
  {
    id: 'destiny_11',
    deck: 'DESTINY',
    title: 'Historic Medina Restoration',
    description: 'Preservation assessment on all your properties: For each Eco-Villa pay $25; For each Grand Citadel pay $100.',
    effect: 'REPAIRS',
    houseFee: 25,
    hotelFee: 100,
    icon: 'wrench',
  },
  {
    id: 'destiny_12',
    deck: 'DESTINY',
    title: 'Highway Velocity Citation',
    description: 'Exceeding trans-Saharan highway speed limits. Pay fine of $15 to the Treasury.',
    effect: 'PAY_BANK',
    value: 15,
    icon: 'alert-triangle',
  },
  {
    id: 'destiny_13',
    deck: 'DESTINY',
    title: 'Board Al Boraq Bullet Train',
    description: 'Take a high-speed journey on Al Boraq High-Speed Rail. If you pass African Gateway, collect $200.',
    effect: 'MOVE_TO',
    targetSpaceId: 5,
    icon: 'train',
  },
  {
    id: 'destiny_14',
    deck: 'DESTINY',
    title: 'Seychelles Sovereign Retreat',
    description: 'Advance to Seychelles Anse Source d\'Argent. The turquoise paradise awaits.',
    effect: 'MOVE_TO',
    targetSpaceId: 39,
    icon: 'crown',
  },
  {
    id: 'destiny_15',
    deck: 'DESTINY',
    title: 'Elected African Economic Council Head',
    description: 'You have been elected President of the African Economic Council. Pay each developer $50 honorarium.',
    effect: 'PAY_PLAYERS',
    value: 50,
    icon: 'users',
  },
  {
    id: 'destiny_16',
    deck: 'DESTINY',
    title: 'Solar Energy Bond Matures',
    description: 'Your Noor Solar development treasury bond matures. Collect $150 from the Bank.',
    effect: 'COLLECT_BANK',
    value: 150,
    icon: 'dollar-sign',
  },
];

export const VAULT_CARDS: Card[] = [
  {
    id: 'vault_1',
    deck: 'VAULT',
    title: 'Advance to African Union Gateway',
    description: 'Advance directly to African Union Gateway (GO). Collect $200 stipend immediately.',
    effect: 'MOVE_TO',
    targetSpaceId: 0,
    icon: 'gate',
  },
  {
    id: 'vault_2',
    deck: 'VAULT',
    title: 'Central Treasury Audit Windfall',
    description: 'Continental treasury audit in your favor. Collect $200 from the Bank.',
    effect: 'COLLECT_BANK',
    value: 200,
    icon: 'file-check',
  },
  {
    id: 'vault_3',
    deck: 'VAULT',
    title: 'Nile Ecological Sanitation Fee',
    description: 'River sanitation and solar clean water assessment. Pay $50 to the Bank.',
    effect: 'PAY_BANK',
    value: 50,
    icon: 'heart-pulse',
  },
  {
    id: 'vault_4',
    deck: 'VAULT',
    title: 'Trans-Continental Rail Yield',
    description: 'From sale of continental high-speed rail shares, you receive $50.',
    effect: 'COLLECT_BANK',
    value: 50,
    icon: 'trending-up',
  },
  {
    id: 'vault_5',
    deck: 'VAULT',
    title: 'Interpol Pardon Pass',
    description: 'This diplomatic pass may be kept until needed, or traded. Releases you immediately from Saharan Detention.',
    effect: 'JAIL_FREE',
    icon: 'key',
  },
  {
    id: 'vault_6',
    deck: 'VAULT',
    title: 'Saharan Detention Warrant',
    description: 'Go directly to Saharan Detention. Do not pass African Gateway. Do not collect $200.',
    effect: 'GO_TO_JAIL',
    icon: 'lock',
  },
  {
    id: 'vault_7',
    deck: 'VAULT',
    title: 'Marrakech International Festival',
    description: 'Grand gala opening in Marrakech. Collect $10 from each developer for VIP seats.',
    effect: 'COLLECT_PLAYERS',
    value: 10,
    icon: 'ticket',
  },
  {
    id: 'vault_8',
    deck: 'VAULT',
    title: 'Sovereign Heritage Trust Yield',
    description: 'African heritage endowment matures. Receive $100.',
    effect: 'COLLECT_BANK',
    value: 100,
    icon: 'gift',
  },
  {
    id: 'vault_9',
    deck: 'VAULT',
    title: 'Trade Directorate Tax Rebate',
    description: 'Import rebate from the Pan-African Trade Directorate. Collect $20.',
    effect: 'COLLECT_BANK',
    value: 20,
    icon: 'coins',
  },
  {
    id: 'vault_10',
    deck: 'VAULT',
    title: 'Founder Jubilee Day',
    description: 'It is your Founder Jubilee Day. Collect $10 from each developer.',
    effect: 'COLLECT_PLAYERS',
    value: 10,
    icon: 'cake',
  },
  {
    id: 'vault_11',
    deck: 'VAULT',
    title: 'Sovereign Life Assurance Matures',
    description: 'Pan-African Life Assurance policy matures. Collect $100.',
    effect: 'COLLECT_BANK',
    value: 100,
    icon: 'shield-check',
  },
  {
    id: 'vault_12',
    deck: 'VAULT',
    title: 'Desert Medical Foundation Grant',
    description: 'Contribution to Saharan Mobile Clinics. Pay $100 to the Bank.',
    effect: 'PAY_BANK',
    value: 100,
    icon: 'building',
  },
  {
    id: 'vault_13',
    deck: 'VAULT',
    title: 'African Academy Endowment',
    description: 'Endowment scholarship for Architecture & Engineering Academy. Pay $50 to the Bank.',
    effect: 'PAY_BANK',
    value: 50,
    icon: 'graduation-cap',
  },
  {
    id: 'vault_14',
    deck: 'VAULT',
    title: 'Urban Planning Consultancy Retainer',
    description: 'Receive $25 consultancy fee for landmark engineering advisory.',
    effect: 'COLLECT_BANK',
    value: 25,
    icon: 'briefcase',
  },
  {
    id: 'vault_15',
    deck: 'VAULT',
    title: 'Oasis Infrastructure Assessment',
    description: 'You are assessed for oasis solar repairs: Pay $40 per Eco-Villa and $115 per Grand Citadel.',
    effect: 'REPAIRS',
    houseFee: 40,
    hotelFee: 115,
    icon: 'hammer',
  },
  {
    id: 'vault_16',
    deck: 'VAULT',
    title: 'Grand Prize in African Architecture',
    description: 'You won the Grand Prize in Pan-African Architecture & Design. Collect $10.',
    effect: 'COLLECT_BANK',
    value: 10,
    icon: 'award',
  },
];
